<?php

namespace Database\Seeders;

use App\Models\anggota;
use App\Models\komponen_gaji;
use App\Models\penggajian;
use App\Models\User;
// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        User::insert([
            [
                'username' => 'admin',
                'password' => Hash::make('admin123'),
                'email' => 'thoriq@simanjuntak.com',
                'nama_depan' => 'Thoriq',
                'nama_belakang' => 'Simanjuntak',
                'role' => 'Admin',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => 'citizen',
                'password' => Hash::make('public123'),
                'email' => 'richard@subakat.com',
                'nama_depan' => 'Richard',
                'nama_belakang' => 'Subakat',
                'role' => 'Public',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        anggota::insert([
            [
                'id_anggota' => 101,
                'nama_depan' => 'Puan',
                'nama_belakang' => 'Maharani',
                'gelar_depan' => 'Dr. (H.C.)',
                'gelar_belakang' => 'S.Sos',
                'jabatan' => 'Ketua',
                'status_pernikahan' => 'Menikah',
                'jumlah_anak' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_anggota' => 102,
                'nama_depan' => 'Lodewijk',
                'nama_belakang' => 'Paulus',
                'gelar_depan' => NULL,
                'gelar_belakang' => NULL,
                'jabatan' => 'Wakil Ketua',
                'status_pernikahan' => 'Menikah',
                'jumlah_anak' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_anggota' => 103,
                'nama_depan' => 'Fadli',
                'nama_belakang' => 'Zon',
                'gelar_depan' => 'Dr.',
                'gelar_belakang' => 'S.S., M.Sc.',
                'jabatan' => 'Anggota',
                'status_pernikahan' => 'Menikah',
                'jumlah_anak' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_anggota' => 104,
                'nama_depan' => 'Sufmi',
                'nama_belakang' => 'Dasco',
                'gelar_depan' => 'Prof. Dr. Ir. H.',
                'gelar_belakang' => 'S.H., M.H.',
                'jabatan' => 'Wakil Ketua',
                'status_pernikahan' => 'Menikah',
                'jumlah_anak' => 11,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_anggota' => 105,
                'nama_depan' => 'Muhaimin',
                'nama_belakang' => 'Iskandar',
                'gelar_depan' => 'Dr (HC). Drs.',
                'gelar_belakang' => NULL,
                'jabatan' => 'Anggota',
                'status_pernikahan' => 'Menikah',
                'jumlah_anak' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_anggota' => 106,
                'nama_depan' => 'Herman',
                'nama_belakang' => 'Hery',
                'gelar_depan' => NULL,
                'gelar_belakang' => NULL,
                'jabatan' => 'Anggota',
                'status_pernikahan' => 'Belum Menikah',
                'jumlah_anak' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        komponen_gaji::insert([
            [
                'id_komponen_gaji' => 201,
                'nama_komponen' => 'Gaji Pokok Ketua',
                'kategori' => 'Gaji Pokok',
                'jabatan' => 'Ketua',
                'nominal' => 5040000.00,
                'satuan' => 'Bulan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_komponen_gaji' => 202,
                'nama_komponen' => 'Gaji Pokok Wakil Ketua',
                'kategori' => 'Gaji Pokok',
                'jabatan' => 'Wakil Ketua',
                'nominal' => 4620000.00,
                'satuan' => 'Bulan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_komponen_gaji' => 203,
                'nama_komponen' => 'Gaji Pokok Anggota',
                'kategori' => 'Gaji Pokok',
                'jabatan' => 'Anggota',
                'nominal' => 4200000.00,
                'satuan' => 'Bulan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        komponen_gaji::insert([
            [
                'id_komponen_gaji' => 204,
                'nama_komponen' => 'Tunjangan Istri/Suami',
                'kategori' => 'Tunjangan Melekat',
                'jabatan' => 'Semua',
                'nominal' => 420000.00,
                'satuan' => 'Bulan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_komponen_gaji' => 205,
                'nama_komponen' => 'Tunjangan Anak',
                'kategori' => 'Tunjangan Melekat',
                'jabatan' => 'Semua',
                'nominal' => 168000.00,
                'satuan' => 'Bulan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_komponen_gaji' => 206,
                'nama_komponen' => 'Uang Sidang/Paket',
                'kategori' => 'Tunjangan Melekat',
                'jabatan' => 'Semua',
                'nominal' => 2000000.00,
                'satuan' => 'Bulan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_komponen_gaji' => 207,
                'nama_komponen' => 'Tunjangan Jabatan Ketua',
                'kategori' => 'Tunjangan Melekat',
                'jabatan' => 'Ketua',
                'nominal' => 18900000.00,
                'satuan' => 'Bulan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_komponen_gaji' => 208,
                'nama_komponen' => 'Tunjangan Jabatan Wakil Ketua',
                'kategori' => 'Tunjangan Melekat',
                'jabatan' => 'Wakil Ketua',
                'nominal' => 15600000.00,
                'satuan' => 'Bulan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_komponen_gaji' => 209,
                'nama_komponen' => 'Tunjangan Jabatan Anggota',
                'kategori' => 'Tunjangan Melekat',
                'jabatan' => 'Anggota',
                'nominal' => 9700000.00,
                'satuan' => 'Bulan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_komponen_gaji' => 210,
                'nama_komponen' => 'Tunjangan Beras',
                'kategori' => 'Tunjangan Melekat',
                'jabatan' => 'Semua',
                'nominal' => 12000000.00,
                'satuan' => 'Bulan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        komponen_gaji::insert([
            [
                'id_komponen_gaji' => 213,
                'nama_komponen' => 'Tunjangan Kehormatan Ketua',
                'kategori' => 'Tunjangan Lain',
                'jabatan' => 'Ketua',
                'nominal' => 6690000.00,
                'satuan' => 'Bulan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_komponen_gaji' => 214,
                'nama_komponen' => 'Tunjangan Kehormatan Wakil Ketua',
                'kategori' => 'Tunjangan Lain',
                'jabatan' => 'Wakil Ketua',
                'nominal' => 6450000.00,
                'satuan' => 'Bulan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_komponen_gaji' => 215,
                'nama_komponen' => 'Tunjangan Kehormatan Anggota',
                'kategori' => 'Tunjangan Lain',
                'jabatan' => 'Anggota',
                'nominal' => 5580000.00,
                'satuan' => 'Bulan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_komponen_gaji' => 216,
                'nama_komponen' => 'Tunjangan Komunikasi Ketua',
                'kategori' => 'Tunjangan Lain',
                'jabatan' => 'Ketua',
                'nominal' => 16468000.00,
                'satuan' => 'Bulan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_komponen_gaji' => 217,
                'nama_komponen' => 'Tunjangan Komunikasi Wakil Ketua',
                'kategori' => 'Tunjangan Lain',
                'jabatan' => 'Wakil Ketua',
                'nominal' => 16009000.00,
                'satuan' => 'Bulan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_komponen_gaji' => 218,
                'nama_komponen' => 'Tunjangan Komunikasi Anggota',
                'kategori' => 'Tunjangan Lain',
                'jabatan' => 'Anggota',
                'nominal' => 15554000.00,
                'satuan' => 'Bulan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_komponen_gaji' => 219,
                'nama_komponen' => 'Tunjangan Fungsi Ketua',
                'kategori' => 'Tunjangan Lain',
                'jabatan' => 'Ketua',
                'nominal' => 5250000.00,
                'satuan' => 'Bulan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_komponen_gaji' => 220,
                'nama_komponen' => 'Tunjangan Fungsi Wakil Ketua',
                'kategori' => 'Tunjangan Lain',
                'jabatan' => 'Wakil Ketua',
                'nominal' => 4500000.00,
                'satuan' => 'Bulan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_komponen_gaji' => 221,
                'nama_komponen' => 'Tunjangan Fungsi Anggota',
                'kategori' => 'Tunjangan Lain',
                'jabatan' => 'Anggota',
                'nominal' => 3750000.00,
                'satuan' => 'Bulan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_komponen_gaji' => 222,
                'nama_komponen' => 'Bantuan Listrik & Telepon',
                'kategori' => 'Tunjangan Lain',
                'jabatan' => 'Semua',
                'nominal' => 7700000.00,
                'satuan' => 'Bulan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_komponen_gaji' => 223,
                'nama_komponen' => 'Asisten Anggota',
                'kategori' => 'Tunjangan Lain',
                'jabatan' => 'Semua',
                'nominal' => 2250000.00,
                'satuan' => 'Bulan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_komponen_gaji' => 224,
                'nama_komponen' => 'Tunjangan Perumahan',
                'kategori' => 'Tunjangan Lain',
                'jabatan' => 'Semua',
                'nominal' => 50000000.00,
                'satuan' => 'Bulan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_komponen_gaji' => 225,
                'nama_komponen' => 'Fasilitas Kredit Mobil',
                'kategori' => 'Tunjangan Lain',
                'jabatan' => 'Semua',
                'nominal' => 70000000.00,
                'satuan' => 'Periode',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        penggajian::insert([
            // Anggota 101 - Ketua DPR (misal)
            ['id_anggota' => 101, 'id_komponen_gaji' => 201, 'created_at' => now(), 'updated_at' => now()],
            ['id_anggota' => 101, 'id_komponen_gaji' => 204, 'created_at' => now(), 'updated_at' => now()],
            ['id_anggota' => 101, 'id_komponen_gaji' => 205, 'created_at' => now(), 'updated_at' => now()],
            ['id_anggota' => 101, 'id_komponen_gaji' => 205, 'created_at' => now(), 'updated_at' => now()],
            ['id_anggota' => 101, 'id_komponen_gaji' => 206, 'created_at' => now(), 'updated_at' => now()],
            ['id_anggota' => 101, 'id_komponen_gaji' => 207, 'created_at' => now(), 'updated_at' => now()],
            ['id_anggota' => 101, 'id_komponen_gaji' => 210, 'created_at' => now(), 'updated_at' => now()],
            ['id_anggota' => 101, 'id_komponen_gaji' => 213, 'created_at' => now(), 'updated_at' => now()],
            ['id_anggota' => 101, 'id_komponen_gaji' => 216, 'created_at' => now(), 'updated_at' => now()],
            ['id_anggota' => 101, 'id_komponen_gaji' => 219, 'created_at' => now(), 'updated_at' => now()],
            ['id_anggota' => 101, 'id_komponen_gaji' => 222, 'created_at' => now(), 'updated_at' => now()],
            ['id_anggota' => 101, 'id_komponen_gaji' => 224, 'created_at' => now(), 'updated_at' => now()],
            ['id_anggota' => 101, 'id_komponen_gaji' => 225, 'created_at' => now(), 'updated_at' => now()],

            // Anggota 102 - Wakil Ketua DPR (Lodewijk)
            ['id_anggota' => 102, 'id_komponen_gaji' => 202, 'created_at' => now(), 'updated_at' => now()],
            ['id_anggota' => 102, 'id_komponen_gaji' => 204, 'created_at' => now(), 'updated_at' => now()],
            ['id_anggota' => 102, 'id_komponen_gaji' => 205, 'created_at' => now(), 'updated_at' => now()],
            ['id_anggota' => 102, 'id_komponen_gaji' => 205, 'created_at' => now(), 'updated_at' => now()],
            ['id_anggota' => 102, 'id_komponen_gaji' => 206, 'created_at' => now(), 'updated_at' => now()],
            ['id_anggota' => 102, 'id_komponen_gaji' => 208, 'created_at' => now(), 'updated_at' => now()],
            ['id_anggota' => 102, 'id_komponen_gaji' => 210, 'created_at' => now(), 'updated_at' => now()],
            ['id_anggota' => 102, 'id_komponen_gaji' => 214, 'created_at' => now(), 'updated_at' => now()],
            ['id_anggota' => 102, 'id_komponen_gaji' => 217, 'created_at' => now(), 'updated_at' => now()],
            ['id_anggota' => 102, 'id_komponen_gaji' => 220, 'created_at' => now(), 'updated_at' => now()],
            ['id_anggota' => 102, 'id_komponen_gaji' => 222, 'created_at' => now(), 'updated_at' => now()],
            ['id_anggota' => 102, 'id_komponen_gaji' => 224, 'created_at' => now(), 'updated_at' => now()],
            ['id_anggota' => 102, 'id_komponen_gaji' => 225, 'created_at' => now(), 'updated_at' => now()],

            // Anggota 103 - Anggota DPR (Fadli)
            ['id_anggota' => 103, 'id_komponen_gaji' => 203, 'created_at' => now(), 'updated_at' => now()],
            ['id_anggota' => 103, 'id_komponen_gaji' => 204, 'created_at' => now(), 'updated_at' => now()],
            ['id_anggota' => 103, 'id_komponen_gaji' => 205, 'created_at' => now(), 'updated_at' => now()],
            ['id_anggota' => 103, 'id_komponen_gaji' => 205, 'created_at' => now(), 'updated_at' => now()],
            ['id_anggota' => 103, 'id_komponen_gaji' => 206, 'created_at' => now(), 'updated_at' => now()],
            ['id_anggota' => 103, 'id_komponen_gaji' => 209, 'created_at' => now(), 'updated_at' => now()],
            ['id_anggota' => 103, 'id_komponen_gaji' => 210, 'created_at' => now(), 'updated_at' => now()],
            ['id_anggota' => 103, 'id_komponen_gaji' => 215, 'created_at' => now(), 'updated_at' => now()],
            ['id_anggota' => 103, 'id_komponen_gaji' => 218, 'created_at' => now(), 'updated_at' => now()],
            ['id_anggota' => 103, 'id_komponen_gaji' => 221, 'created_at' => now(), 'updated_at' => now()],
            ['id_anggota' => 103, 'id_komponen_gaji' => 222, 'created_at' => now(), 'updated_at' => now()],
            ['id_anggota' => 103, 'id_komponen_gaji' => 224, 'created_at' => now(), 'updated_at' => now()],
            ['id_anggota' => 103, 'id_komponen_gaji' => 225, 'created_at' => now(), 'updated_at' => now()],

            // Anggota 104 - Wakil Ketua DPR (Dasco)
            ['id_anggota' => 104, 'id_komponen_gaji' => 202, 'created_at' => now(), 'updated_at' => now()],
            ['id_anggota' => 104, 'id_komponen_gaji' => 204, 'created_at' => now(), 'updated_at' => now()],
            ['id_anggota' => 104, 'id_komponen_gaji' => 205, 'created_at' => now(), 'updated_at' => now()],
            ['id_anggota' => 104, 'id_komponen_gaji' => 205, 'created_at' => now(), 'updated_at' => now()],
            ['id_anggota' => 104, 'id_komponen_gaji' => 206, 'created_at' => now(), 'updated_at' => now()],
            ['id_anggota' => 104, 'id_komponen_gaji' => 208, 'created_at' => now(), 'updated_at' => now()],
            ['id_anggota' => 104, 'id_komponen_gaji' => 210, 'created_at' => now(), 'updated_at' => now()],
            ['id_anggota' => 104, 'id_komponen_gaji' => 214, 'created_at' => now(), 'updated_at' => now()],
            ['id_anggota' => 104, 'id_komponen_gaji' => 217, 'created_at' => now(), 'updated_at' => now()],
            ['id_anggota' => 104, 'id_komponen_gaji' => 220, 'created_at' => now(), 'updated_at' => now()],
            ['id_anggota' => 104, 'id_komponen_gaji' => 222, 'created_at' => now(), 'updated_at' => now()],
            ['id_anggota' => 104, 'id_komponen_gaji' => 224, 'created_at' => now(), 'updated_at' => now()],
            ['id_anggota' => 104, 'id_komponen_gaji' => 225, 'created_at' => now(), 'updated_at' => now()],

            // Anggota 105 - Anggota DPR (Muhaimin)
            ['id_anggota' => 105, 'id_komponen_gaji' => 203, 'created_at' => now(), 'updated_at' => now()],
            ['id_anggota' => 105, 'id_komponen_gaji' => 204, 'created_at' => now(), 'updated_at' => now()],
            ['id_anggota' => 105, 'id_komponen_gaji' => 205, 'created_at' => now(), 'updated_at' => now()],
            ['id_anggota' => 105, 'id_komponen_gaji' => 206, 'created_at' => now(), 'updated_at' => now()],
            ['id_anggota' => 105, 'id_komponen_gaji' => 209, 'created_at' => now(), 'updated_at' => now()],
            ['id_anggota' => 105, 'id_komponen_gaji' => 210, 'created_at' => now(), 'updated_at' => now()],
            ['id_anggota' => 105, 'id_komponen_gaji' => 215, 'created_at' => now(), 'updated_at' => now()],
            ['id_anggota' => 105, 'id_komponen_gaji' => 218, 'created_at' => now(), 'updated_at' => now()],
            ['id_anggota' => 105, 'id_komponen_gaji' => 221, 'created_at' => now(), 'updated_at' => now()],
            ['id_anggota' => 105, 'id_komponen_gaji' => 222, 'created_at' => now(), 'updated_at' => now()],
            ['id_anggota' => 105, 'id_komponen_gaji' => 224, 'created_at' => now(), 'updated_at' => now()],
            ['id_anggota' => 105, 'id_komponen_gaji' => 225, 'created_at' => now(), 'updated_at' => now()],

            // Anggota 106 - Anggota DPR (Herman)
            ['id_anggota' => 106, 'id_komponen_gaji' => 203, 'created_at' => now(), 'updated_at' => now()],
            ['id_anggota' => 106, 'id_komponen_gaji' => 204, 'created_at' => now(), 'updated_at' => now()],
            ['id_anggota' => 106, 'id_komponen_gaji' => 205, 'created_at' => now(), 'updated_at' => now()],
            ['id_anggota' => 106, 'id_komponen_gaji' => 205, 'created_at' => now(), 'updated_at' => now()],
            ['id_anggota' => 106, 'id_komponen_gaji' => 206, 'created_at' => now(), 'updated_at' => now()],
            ['id_anggota' => 106, 'id_komponen_gaji' => 209, 'created_at' => now(), 'updated_at' => now()],
            ['id_anggota' => 106, 'id_komponen_gaji' => 210, 'created_at' => now(), 'updated_at' => now()],
            ['id_anggota' => 106, 'id_komponen_gaji' => 215, 'created_at' => now(), 'updated_at' => now()],
            ['id_anggota' => 106, 'id_komponen_gaji' => 218, 'created_at' => now(), 'updated_at' => now()],
            ['id_anggota' => 106, 'id_komponen_gaji' => 221, 'created_at' => now(), 'updated_at' => now()],
            ['id_anggota' => 106, 'id_komponen_gaji' => 222, 'created_at' => now(), 'updated_at' => now()],
            ['id_anggota' => 106, 'id_komponen_gaji' => 224, 'created_at' => now(), 'updated_at' => now()],
            ['id_anggota' => 106, 'id_komponen_gaji' => 225, 'created_at' => now(), 'updated_at' => now()],
        ]);
    }
}
